use vexilliumDB;
## Nordic
insert into Countries(Countryname, Capital, Flag, Region)
values ('Danmark', 'Köpenhamn', 'https://flagpedia.net/data/flags/w1160/dk.webp', 'Norden'),
       ('Finland', 'Helsinki', 'https://flagpedia.net/data/flags/w1160/fi.webp', 'Norden'),
       ('Island', 'Reykjavik', 'https://flagpedia.net/data/flags/wj160/is.webp', 'Norden'),
       ('Norge', 'Oslo', 'https://flagpedia.net/data/flags/w1160/no.webp', 'Norden'),
       ('Sverige', 'Stockholm', 'https://flagpedia.net/data/flags/w1160/se.webp', 'Norden'),
       ('Åland', 'Mariehamn', 'https://flagpedia.net/data/flags/w1160/ax.webp', 'Norden'),
       ('Färöarna', 'Tórshavn', 'https://flagpedia.net/data/flags/w1160/fo.webp', 'Norden'),
       ('Grönland', 'Nuuk', 'https://flagpedia.net/data/flags/w1160/gl.webp', 'Norden');

## Europe
INSERT INTO Countries(Countryname, Capital, Flag, Region)
VALUES
    ('Albanien', 'Tirana', 'https://flagpedia.net/data/flags/w1160/al.webp', 'Europa'),
    ('Andorra', 'Andorra la Vella', 'https://flagpedia.net/data/flags/w1160/ad.webp', 'Europa'),
    ('Österrike', 'Wien', 'https://flagpedia.net/data/flags/w1160/at.webp', 'Europa'),
    ('Belarus', 'Minsk', 'https://flagpedia.net/data/flags/w1160/by.webp', 'Europa'),
    ('Belgien', 'Bryssel', 'https://flagpedia.net/data/flags/w1160/be.webp', 'Europa'),
    ('Bosnien och Hercegovina', 'Sarajevo', 'https://flagpedia.net/data/flags/w1160/ba.webp', 'Europa'),
    ('Bulgarien', 'Sofia', 'https://flagpedia.net/data/flags/w1160/bg.webp', 'Europa'),
    ('Cypern', 'Nicosia', 'https://flagpedia.net/data/flags/w1160/cy.webp', 'Europa'),
    ('Frankrike', 'Paris', 'https://flagpedia.net/data/flags/w1160/fr.webp', 'Europa'),
    ('Grekland', 'Aten', 'https://flagpedia.net/data/flags/w1160/gr.webp', 'Europa'),
    ('Irland', 'Dublin', 'https://flagpedia.net/data/flags/w1160/ie.webp', 'Europa'),
    ('Italien', 'Rom', 'https://flagpedia.net/data/flags/w1160/it.webp', 'Europa'),
    ('Kosovo', 'Pristina', 'https://flagpedia.net/data/flags/w1160/xk.webp', 'Europa'),
    ('Kroatien', 'Zagreb', 'https://flagpedia.net/data/flags/w1160/hr.webp', 'Europa'),
    ('Lettland', 'Riga', 'https://flagpedia.net/data/flags/w1160/lv.webp', 'Europa'),
    ('Liechtenstein', 'Vaduz', 'https://flagpedia.net/data/flags/w1160/li.webp', 'Europa'),
    ('Litauen', 'Vilnius', 'https://flagpedia.net/data/flags/w1160/lt.webp', 'Europa'),
    ('Luxemburg', 'Luxemburg', 'https://flagpedia.net/data/flags/w1160/lu.webp', 'Europa'),
    ('Malta', 'Valletta', 'https://flagpedia.net/data/flags/w1160/mt.webp', 'Europa'),
    ('Moldavien', 'Chișinău', 'https://flagpedia.net/data/flags/w1160/md.webp', 'Europa'),
    ('Monaco', 'Monaco', 'https://flagpedia.net/data/flags/w1160/mc.webp', 'Europa'),
    ('Montenegro', 'Podgorica', 'https://flagpedia.net/data/flags/w1160/me.webp', 'Europa'),
    ('Nederländerna', 'Amsterdam', 'https://flagpedia.net/data/flags/w1160/nl.webp', 'Europa'),
    ('Nordmakedonien', 'Skopje', 'https://flagpedia.net/data/flags/w1160/mk.webp', 'Europa'),
    ('Polen', 'Warszawa', 'https://flagpedia.net/data/flags/w1160/pl.webp', 'Europa'),
    ('Portugal', 'Lissabon', 'https://flagpedia.net/data/flags/w1160/pt.webp', 'Europa'),
    ('Rumänien', 'Bukarest', 'https://flagpedia.net/data/flags/w1160/ro.webp', 'Europa'),
    ('Ryssland', 'Moskva', 'https://flagpedia.net/data/flags/w1160/ru.webp', 'Europa'),
    ('San Marino', 'San Marino', 'https://flagpedia.net/data/flags/w1160/sm.webp', 'Europa'),
    ('Schweiz', 'Bern', 'https://flagpedia.net/data/flags/w1160/ch.webp', 'Europa'),
    ('Serbien', 'Belgrad', 'https://flagpedia.net/data/flags/w1160/rs.webp', 'Europa'),
    ('Slovakien', 'Bratislava', 'https://flagpedia.net/data/flags/w1160/sk.webp', 'Europa'),
    ('Slovenien', 'Ljubljana', 'https://flagpedia.net/data/flags/w1160/si.webp', 'Europa'),
    ('Spanien', 'Madrid', 'https://flagpedia.net/data/flags/w1160/es.webp', 'Europa'),
    ('Storbritannien', 'London', 'https://flagpedia.net/data/flags/w1160/gb.webp', 'Europa'),
    ('Tjeckien', 'Prag', 'https://flagpedia.net/data/flags/w1160/cz.webp', 'Europa'),
    ('Turkiet', 'Ankara', 'https://flagpedia.net/data/flags/w1160/tr.webp', 'Europa'),
    ('Tyskland', 'Berlin', 'https://flagpedia.net/data/flags/w1160/de.webp', 'Europa'),
    ('Ukraina', 'Kyiv', 'https://flagpedia.net/data/flags/w1160/ua.webp', 'Europa'),
    ('Ungern', 'Budapest', 'https://flagpedia.net/data/flags/w1160/hu.webp', 'Europa'),
    ('Vatikanstaten', 'Vatikanstaten', 'https://flagpedia.net/data/flags/w1160/va.webp', 'Europa');

## Afrika
INSERT INTO Countries(Countryname, Capital, Flag, Region)
VALUES
    ('Algeriet', 'Alger', 'https://flagpedia.net/data/flags/w1160/dz.webp', 'Afrika'),
    ('Angola', 'Luanda', 'https://flagpedia.net/data/flags/w1160/ao.webp', 'Afrika'),
    ('Benin', 'Porto-Novo', 'https://flagpedia.net/data/flags/w1160/bj.webp', 'Afrika'),
    ('Botswana', 'Gaborone', 'https://flagpedia.net/data/flags/w1160/bw.webp', 'Afrika'),
    ('Burkina Faso', 'Ouagadougou', 'https://flagpedia.net/data/flags/w1160/bf.webp', 'Afrika'),
    ('Burundi', 'Gitega', 'https://flagpedia.net/data/flags/w1160/bi.webp', 'Afrika'),
    ('Centralafrikanska republiken', 'Bangui', 'https://flagpedia.net/data/flags/w1160/cf.webp', 'Afrika'),
    ('Demokratiska republiken Kongo', 'Kinshasa', 'https://flagpedia.net/data/flags/w1160/cd.webp', 'Afrika'),
    ('Djibouti', 'Djibouti', 'https://flagpedia.net/data/flags/w1160/dj.webp', 'Afrika'),
    ('Egypten', 'Kairo', 'https://flagpedia.net/data/flags/w1160/eg.webp', 'Afrika'),
    ('Ekvatorialguinea', 'Ciudad de la Paz', 'https://flagpedia.net/data/flags/w1160/gq.webp', 'Afrika'),
    ('Elfenbenskusten', 'Yamoussoukro', 'https://flagpedia.net/data/flags/w1160/ci.webp', 'Afrika'),
    ('Eritrea', 'Asmara', 'https://flagpedia.net/data/flags/w1160/er.webp', 'Afrika'),
    ('Eswatini', 'Mbabane', 'https://flagpedia.net/data/flags/w1160/sz.webp', 'Afrika'),
    ('Etiopien', 'Addis Abeba', 'https://flagpedia.net/data/flags/w1160/et.webp', 'Afrika'),
    ('Gabon', 'Libreville', 'https://flagpedia.net/data/flags/w1160/ga.webp', 'Afrika'),
    ('Gambia', 'Banjul', 'https://flagpedia.net/data/flags/w1160/gm.webp', 'Afrika'),
    ('Ghana', 'Accra', 'https://flagpedia.net/data/flags/w1160/gh.webp', 'Afrika'),
    ('Guinea', 'Conakry', 'https://flagpedia.net/data/flags/w1160/gn.webp', 'Afrika'),
    ('Guinea-Bissau', 'Bissau', 'https://flagpedia.net/data/flags/w1160/gw.webp', 'Afrika'),
    ('Kamerun', 'Yaoundé', 'https://flagpedia.net/data/flags/w1160/cm.webp', 'Afrika'),
    ('Kap Verde', 'Praia', 'https://flagpedia.net/data/flags/w1160/cv.webp', 'Afrika'),
    ('Kenya', 'Nairobi', 'https://flagpedia.net/data/flags/w1160/ke.webp', 'Afrika'),
    ('Komorerna', 'Moroni', 'https://flagpedia.net/data/flags/w1160/km.webp', 'Afrika'),
    ('Kongo-Brazzaville', 'Brazzaville', 'https://flagpedia.net/data/flags/w1160/cg.webp', 'Afrika'),
    ('Lesotho', 'Maseru', 'https://flagpedia.net/data/flags/w1160/ls.webp', 'Afrika'),
    ('Liberia', 'Monrovia', 'https://flagpedia.net/data/flags/w1160/lr.webp', 'Afrika'),
    ('Libyen', 'Tripoli', 'https://flagpedia.net/data/flags/w1160/ly.webp', 'Afrika'),
    ('Madagaskar', 'Antananarivo', 'https://flagpedia.net/data/flags/w1160/mg.webp', 'Afrika'),
    ('Malawi', 'Lilongwe', 'https://flagpedia.net/data/flags/w1160/mw.webp', 'Afrika'),
    ('Mali', 'Bamako', 'https://flagpedia.net/data/flags/w1160/ml.webp', 'Afrika'),
    ('Marocko', 'Rabat', 'https://flagpedia.net/data/flags/w1160/ma.webp', 'Afrika'),
    ('Mauretanien', 'Nouakchott', 'https://flagpedia.net/data/flags/w1160/mr.webp', 'Afrika'),
    ('Mauritius', 'Port Louis', 'https://flagpedia.net/data/flags/w1160/mu.webp', 'Afrika'),
    ('Moçambique', 'Maputo', 'https://flagpedia.net/data/flags/w1160/mz.webp', 'Afrika'),
    ('Namibia', 'Windhoek', 'https://flagpedia.net/data/flags/w1160/na.webp', 'Afrika'),
    ('Niger', 'Niamey', 'https://flagpedia.net/data/flags/w1160/ne.webp', 'Afrika'),
    ('Nigeria', 'Abuja', 'https://flagpedia.net/data/flags/w1160/ng.webp', 'Afrika'),
    ('Rwanda', 'Kigali', 'https://flagpedia.net/data/flags/w1160/rw.webp', 'Afrika'),
    ('São Tomé och Príncipe', 'São Tomé', 'https://flagpedia.net/data/flags/w1160/st.webp', 'Afrika'),
    ('Senegal', 'Dakar', 'https://flagpedia.net/data/flags/w1160/sn.webp', 'Afrika'),
    ('Seychellerna', 'Victoria', 'https://flagpedia.net/data/flags/w1160/sc.webp', 'Afrika'),
    ('Sierra Leone', 'Freetown', 'https://flagpedia.net/data/flags/w1160/sl.webp', 'Afrika'),
    ('Somalia', 'Mogadishu', 'https://flagpedia.net/data/flags/w1160/so.webp', 'Afrika'),
    ('Sudan', 'Khartoum', 'https://flagpedia.net/data/flags/w1160/sd.webp', 'Afrika'),
    ('Sydafrika', 'Pretoria', 'https://flagpedia.net/data/flags/w1160/za.webp', 'Afrika'),
    ('Sydsudan', 'Juba', 'https://flagpedia.net/data/flags/w1160/ss.webp', 'Afrika'),
    ('Tanzania', 'Dodoma', 'https://flagpedia.net/data/flags/w1160/tz.webp', 'Afrika'),
    ('Tchad', 'N’Djamena', 'https://flagpedia.net/data/flags/w1160/td.webp', 'Afrika'),
    ('Togo', 'Lomé', 'https://flagpedia.net/data/flags/w1160/tg.webp', 'Afrika'),
    ('Tunisien', 'Tunis', 'https://flagpedia.net/data/flags/w1160/tn.webp', 'Afrika'),
    ('Uganda', 'Kampala', 'https://flagpedia.net/data/flags/w1160/ug.webp', 'Afrika'),
    ('Zambia', 'Lusaka', 'https://flagpedia.net/data/flags/w1160/zm.webp', 'Afrika'),
    ('Zimbabwe', 'Harare', 'https://flagpedia.net/data/flags/w1160/zw.webp', 'Afrika')
;

# North America
INSERT INTO Countries(Countryname, Capital, Flag, Region)
VALUES
    ('Antigua och Barbuda', 'Saint John’s', 'https://flagpedia.net/data/flags/w1160/ag.webp', 'Nord Amerika'),
    ('Bahamas', 'Nassau', 'https://flagpedia.net/data/flags/w1160/bs.webp', 'Nord Amerika'),
    ('Barbados', 'Bridgetown', 'https://flagpedia.net/data/flags/w1160/bb.webp', 'Nord Amerika'),
    ('Belize', 'Belmopan', 'https://flagpedia.net/data/flags/w1160/bz.webp', 'Nord Amerika'),
    ('Canada', 'Ottawa', 'https://flagpedia.net/data/flags/w1160/ca.webp', 'Nord Amerika'),
    ('Costa Rica', 'San José', 'https://flagpedia.net/data/flags/w1160/cr.webp', 'Nord Amerika'),
    ('Cuba', 'Havanna', 'https://flagpedia.net/data/flags/w1160/cu.webp', 'Nord Amerika'),
    ('Dominica', 'Roseau', 'https://flagpedia.net/data/flags/w1160/dm.webp', 'Nord Amerika'),
    ('Dominikanska republiken', 'Santo Domingo', 'https://flagpedia.net/data/flags/w1160/do.webp', 'Nord Amerika'),
    ('El Salvador', 'San Salvador', 'https://flagpedia.net/data/flags/w1160/sv.webp', 'Nord Amerika'),
    ('Grenada', 'Saint George’s', 'https://flagpedia.net/data/flags/w1160/gd.webp', 'Nord Amerika'),
    ('Guatemala', 'Guatemala City', 'https://flagpedia.net/data/flags/w1160/gt.webp', 'Nord Amerika'),
    ('Haiti', 'Port-au-Prince', 'https://flagpedia.net/data/flags/w1160/ht.webp', 'Nord Amerika'),
    ('Honduras', 'Tegucigalpa', 'https://flagpedia.net/data/flags/w1160/hn.webp', 'Nord Amerika'),
    ('Jamaica', 'Kingston', 'https://flagpedia.net/data/flags/w1160/jm.webp', 'Nord Amerika'),
    ('Mexiko', 'Mexico City', 'https://flagpedia.net/data/flags/w1160/mx.webp', 'Nord Amerika'),
    ('Nicaragua', 'Managua', 'https://flagpedia.net/data/flags/w1160/ni.webp', 'Nord Amerika'),
    ('Panama', 'Panama City', 'https://flagpedia.net/data/flags/w1160/pa.webp', 'Nord Amerika'),
    ('Saint Kitts och Nevis', 'Basseterre', 'https://flagpedia.net/data/flags/w1160/kn.webp', 'Nord Amerika'),
    ('Saint Lucia', 'Castries', 'https://flagpedia.net/data/flags/w1160/lc.webp', 'Nord Amerika'),
    ('Saint Vincent och Grenadinerna', 'Kingstown', 'https://flagpedia.net/data/flags/w1160/vc.webp', 'Nord Amerika'),
    ('Trinidad och Tobago', 'Port of Spain', 'https://flagpedia.net/data/flags/w1160/tt.webp', 'Nord Amerika'),
    ('USA', 'Washington D.C.', 'https://flagpedia.net/data/flags/w1160/us.webp', 'Nord Amerika')
;

# Central America
INSERT INTO Countries(Countryname, Capital, Flag, Region)
VALUES
    ('Belize', 'Belmopan', 'https://flagpedia.net/data/flags/w1160/bz.webp', 'Central Amerika'),
    ('Costa Rica', 'San José', 'https://flagpedia.net/data/flags/w1160/cr.webp', 'Central Amerika'),
    ('El Salvador', 'San Salvador', 'https://flagpedia.net/data/flags/w1160/sv.webp', 'Central Amerika'),
    ('Guatemala', 'Guatemala City', 'https://flagpedia.net/data/flags/w1160/gt.webp', 'Central Amerika'),
    ('Honduras', 'Tegucigalpa', 'https://flagpedia.net/data/flags/w1160/hn.webp', 'Central Amerika'),
    ('Nicaragua', 'Managua', 'https://flagpedia.net/data/flags/w1160/ni.webp', 'Central Amerika'),
    ('Panama', 'Panama City', 'https://flagpedia.net/data/flags/w1160/pa.webp', 'Central Amerika');

# South America

INSERT INTO Countries(Countryname, Capital, Flag, Region)
VALUES
    ('Argentina', 'Buenos Aires', 'https://flagpedia.net/data/flags/w1160/ar.webp', 'Syd Amerika'),
    ('Bolivia', 'Sucre', 'https://flagpedia.net/data/flags/w1160/bo.webp', 'Syd Amerika'),
    ('Brasilien', 'Brasília', 'https://flagpedia.net/data/flags/w1160/br.webp', 'Syd Amerika'),
    ('Chile', 'Santiago', 'https://flagpedia.net/data/flags/w1160/cl.webp', 'Syd Amerika'),
    ('Colombia', 'Bogotá', 'https://flagpedia.net/data/flags/w1160/co.webp', 'Syd Amerika'),
    ('Ecuador', 'Quito', 'https://flagpedia.net/data/flags/w1160/ec.webp', 'Syd Amerika'),
    ('Guyana', 'Georgetown', 'https://flagpedia.net/data/flags/w1160/gy.webp', 'Syd Amerika'),
    ('Paraguay', 'Asunción', 'https://flagpedia.net/data/flags/w1160/py.webp', 'Syd Amerika'),
    ('Peru', 'Lima', 'https://flagpedia.net/data/flags/w1160/pe.webp', 'Syd Amerika'),
    ('Surinam', 'Paramaribo', 'https://flagpedia.net/data/flags/w1160/sr.webp', 'Syd Amerika'),
    ('Uruguay', 'Montevideo', 'https://flagpedia.net/data/flags/w1160/uy.webp', 'Syd Amerika'),
    ('Venezuela', 'Caracas', 'https://flagpedia.net/data/flags/w1160/ve.webp', 'Syd Amerika');


# Asia

INSERT INTO Countries(Countryname, Capital, Flag, Region)
VALUES
    ('Afghanistan', 'Kabul', 'https://flagpedia.net/data/flags/w1160/af.webp', 'Asien'),
    ('Armenien', 'Jerevan', 'https://flagpedia.net/data/flags/w1160/am.webp', 'Asien'),
    ('Azerbajdzjan', 'Baku', 'https://flagpedia.net/data/flags/w1160/az.webp', 'Asien'),
    ('Bahrain', 'Manama', 'https://flagpedia.net/data/flags/w1160/bh.webp', 'Asien'),
    ('Bangladesh', 'Dhaka', 'https://flagpedia.net/data/flags/w1160/bd.webp', 'Asien'),
    ('Bhutan', 'Thimphu', 'https://flagpedia.net/data/flags/w1160/bt.webp', 'Asien'),
    ('Brunei', 'Bandar Seri Begawan', 'https://flagpedia.net/data/flags/w1160/bn.webp', 'Asien'),
    ('Cypern', 'Nicosia', 'https://flagpedia.net/data/flags/w1160/cy.webp', 'Asien'),
    ('Filippinerna', 'Manila', 'https://flagpedia.net/data/flags/w1160/ph.webp', 'Asien'),
    ('Förenade Arabemiraten', 'Abu Dhabi', 'https://flagpedia.net/data/flags/w1160/ae.webp', 'Asien'),
    ('Georgien', 'Tbilisi', 'https://flagpedia.net/data/flags/w1160/ge.webp', 'Asien'),
    ('Indien', 'New Delhi', 'https://flagpedia.net/data/flags/w1160/in.webp', 'Asien'),
    ('Indonesien', 'Jakarta', 'https://flagpedia.net/data/flags/w1160/id.webp', 'Asien'),
    ('Irak', 'Bagdad', 'https://flagpedia.net/data/flags/w1160/iq.webp', 'Asien'),
    ('Iran', 'Teheran', 'https://flagpedia.net/data/flags/w1160/ir.webp', 'Asien'),
    ('Israel', 'Jerusalem', 'https://flagpedia.net/data/flags/w1160/il.webp', 'Asien'),
    ('Japan', 'Tokyo', 'https://flagpedia.net/data/flags/w1160/jp.webp', 'Asien'),
    ('Jemen', 'Sana’a', 'https://flagpedia.net/data/flags/w1160/ye.webp', 'Asien'),
    ('Jordanien', 'Amman', 'https://flagpedia.net/data/flags/w1160/jo.webp', 'Asien'),
    ('Kambodja', 'Phnom Penh', 'https://flagpedia.net/data/flags/w1160/kh.webp', 'Asien'),
    ('Kazakstan', 'Astana', 'https://flagpedia.net/data/flags/w1160/kz.webp', 'Asien'),
    ('Kina', 'Peking', 'https://flagpedia.net/data/flags/w1160/cn.webp', 'Asien'),
    ('Kirgizistan', 'Bisjkek', 'https://flagpedia.net/data/flags/w1160/kg.webp', 'Asien'),
    ('Kuwait', 'Kuwait City', 'https://flagpedia.net/data/flags/w1160/kw.webp', 'Asien'),
    ('Laos', 'Vientiane', 'https://flagpedia.net/data/flags/w1160/la.webp', 'Asien'),
    ('Libanon', 'Beirut', 'https://flagpedia.net/data/flags/w1160/lb.webp', 'Asien'),
    ('Malaysia', 'Kuala Lumpur', 'https://flagpedia.net/data/flags/w1160/my.webp', 'Asien'),
    ('Maldiverna', 'Malé', 'https://flagpedia.net/data/flags/w1160/mv.webp', 'Asien'),
    ('Mongoliet', 'Ulan Bator', 'https://flagpedia.net/data/flags/w1160/mn.webp', 'Asien'),
    ('Myanmar', 'Naypyidaw', 'https://flagpedia.net/data/flags/w1160/mm.webp', 'Asien'),
    ('Nepal', 'Kathmandu', 'https://flagpedia.net/data/flags/w1160/np.webp', 'Asien'),
    ('Nordkorea', 'Pyongyang', 'https://flagpedia.net/data/flags/w1160/kp.webp', 'Asien'),
    ('Oman', 'Muskat', 'https://flagpedia.net/data/flags/w1160/om.webp', 'Asien'),
    ('Pakistan', 'Islamabad', 'https://flagpedia.net/data/flags/w1160/pk.webp', 'Asien'),
    ('Palestina', 'Ramallah', 'https://flagpedia.net/data/flags/w1160/ps.webp', 'Asien'),
    ('Qatar', 'Doha', 'https://flagpedia.net/data/flags/w1160/qa.webp', 'Asien'),
    ('Saudiarabien', 'Riyadh', 'https://flagpedia.net/data/flags/w1160/sa.webp', 'Asien'),
    ('Singapore', 'Singapore', 'https://flagpedia.net/data/flags/w1160/sg.webp', 'Asien'),
    ('Sri Lanka', 'Sri Jayawardenepura Kotte', 'https://flagpedia.net/data/flags/w1160/lk.webp', 'Asien'),
    ('Sydkorea', 'Seoul', 'https://flagpedia.net/data/flags/w1160/kr.webp', 'Asien'),
    ('Syrien', 'Damaskus', 'https://flagpedia.net/data/flags/w1160/sy.webp', 'Asien'),
    ('Tadzjikistan', 'Dusjanbe', 'https://flagpedia.net/data/flags/w1160/tj.webp', 'Asien'),
    ('Thailand', 'Bangkok', 'https://flagpedia.net/data/flags/w1160/th.webp', 'Asien'),
    ('Turkmenistan', 'Asjchabad', 'https://flagpedia.net/data/flags/w1160/tm.webp', 'Asien'),
    ('Turkiet', 'Ankara', 'https://flagpedia.net/data/flags/w1160/tr.webp', 'Asien'),
    ('Uzbekistan', 'Tasjkent', 'https://flagpedia.net/data/flags/w1160/uz.webp', 'Asien'),
    ('Vietnam', 'Hanoi', 'https://flagpedia.net/data/flags/w1160/vn.webp', 'Asien'),
    ('Östtimor', 'Dili', 'https://flagpedia.net/data/flags/w1160/tl.webp', 'Asien');

# Oceanien

INSERT INTO Countries(Countryname, Capital, Flag, Region)
VALUES
    ('Australien', 'Canberra', 'https://flagpedia.net/data/flags/w1160/au.webp', 'Ocianien'),
    ('Fiji', 'Suva', 'https://flagpedia.net/data/flags/w1160/fj.webp', 'Ocianien'),
    ('Kiribati', 'South Tarawa', 'https://flagpedia.net/data/flags/w1160/ki.webp', 'Ocianien'),
    ('Marshallöarna', 'Majuro', 'https://flagpedia.net/data/flags/w1160/mh.webp', 'Ocianien'),
    ('Mikronesien', 'Palikir', 'https://flagpedia.net/data/flags/w1160/fm.webp', 'Ocianien'),
    ('Nauru', 'Yaren', 'https://flagpedia.net/data/flags/w1160/nr.webp', 'Ocianien'),
    ('Nya Zeeland', 'Wellington', 'https://flagpedia.net/data/flags/w1160/nz.webp', 'Ocianien'),
    ('Palau', 'Ngerulmud', 'https://flagpedia.net/data/flags/w1160/pw.webp', 'Ocianien'),
    ('Papua Nya Guinea', 'Port Moresby', 'https://flagpedia.net/data/flags/w1160/pg.webp', 'Ocianien'),
    ('Samoa', 'Apia', 'https://flagpedia.net/data/flags/w1160/ws.webp', 'Ocianien'),
    ('Salomonöarna', 'Honiara', 'https://flagpedia.net/data/flags/w1160/sb.webp', 'Ocianien'),
    ('Tonga', 'Nuku''alofa', 'https://flagpedia.net/data/flags/w1160/to.webp', 'Ocianien'),
    ('Tuvalu', 'Funafuti', 'https://flagpedia.net/data/flags/w1160/tv.webp', 'Ocianien'),
    ('Vanuatu', 'Port Vila', 'https://flagpedia.net/data/flags/w1160/vu.webp', 'Ocianien');

